name: t_kairos_shop
description: Premium Sakura Style Flutter App
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  supabase_flutter: ^2.0.0
  flutter_riverpod: ^2.4.0
  google_sign_in: ^6.1.5
  cached_network_image: ^3.3.0
  flutter_svg: ^2.0.9
  animations: ^2.0.8
  intl: ^0.20.2 # For currency formatting
  image_picker: ^1.2.1
  video_player: ^2.10.1
  video_player_win: ^3.2.2
  visibility_detector: ^0.4.0+2
  record: ^6.1.2
  audioplayers: ^6.5.1
  path_provider: ^2.1.5
  permission_handler: ^12.0.1
  http: ^1.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  # Add this section:
  assets:
    - asset/logo.png